version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "4040:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - clickhouse
      - php
  php:
    image: php:8.0.2-fpm-alpine3.13
    container_name: php
    volumes:
      - ./php/config/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      - ./app:/var/www/html
  clickhouse:
    container_name: clickhouse
    image: yandex/clickhouse-server:20-alpine
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse:/var/lib/clickhouse:rw
      - ./clickhouse/config/config.xml:/etc/clickhouse-server/config.xml:ro
      - ./clickhouse/scheme:/docker-entrypoint-initdb.d:ro
  logstash:
    image: docker.elastic.co/logstash/logstash:7.11.1
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper:/bitnami/zookeeper
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    volumes:
      - kafka:/bitnami/kafka
    depends_on:
      - zookeeper

volumes:
  clickhouse: {}
  zookeeper: {}
  kafka: {}
